version: '3.8'

services:
  server:
    image: server-app
    ports: 
      - 8081:8081
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - BUILD_COMMAND=${BUILD_COMMAND}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BUILD_COMMAND: ${BUILD_COMMAND} 
      JWT_SECRET: ${JWT_SECRET}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_URL: ${MONGO_URL}
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8080:8080"
volumes:
  mongodb_data: